import { ModuleConfig, NavItem } from "@/src/types/navigation";

export const PRODUCT_NAV_ITEMS: readonly NavItem[] = [
  { label: "Dashboard", href: "/", icon: "DB", description: "AI mission control", slug: "dashboard" },
  { label: "AI Missions", href: "/missions", icon: "AI", description: "Guided execution cards", slug: "missions" },
  { label: "Product Studio", href: "/product-studio", icon: "PS", description: "Product portfolio lifecycle", slug: "product-studio" },
  { label: "Market Intelligence", href: "/market-intelligence", icon: "MI", description: "Market and competitor signal", slug: "market-intelligence" },
  { label: "Requirements", href: "/requirements", icon: "RQ", description: "PRD and design constraints", slug: "requirements" },
  { label: "CAD Studio", href: "/cad-studio", icon: "CD", description: "CAD files and revisions", slug: "cad-studio" },
  { label: "Material Studio", href: "/material-studio", icon: "MT", description: "Materials and stock", slug: "material-studio" },
  { label: "Cost Studio", href: "/cost-studio", icon: "CS", description: "Costing and profitability", slug: "cost-studio" },
  { label: "Prototype Studio", href: "/prototype-studio", icon: "PT", description: "Prototype test loop", slug: "prototype-studio" },
  { label: "Manufacturing Studio", href: "/manufacturing-studio", icon: "MF", description: "Machines and instructions", slug: "manufacturing-studio" },
  { label: "Production Studio", href: "/production-studio", icon: "PD", description: "Production orders and jobs", slug: "production-studio" },
  { label: "Inventory Studio", href: "/inventory-studio", icon: "IV", description: "Raw and finished goods", slug: "inventory-studio" },
  { label: "Sales Studio", href: "/sales-studio", icon: "SL", description: "Channels and revenue", slug: "sales-studio" },
  { label: "AI Studio", href: "/ai-studio", icon: "AS", description: "Assistant and copilot tasks", slug: "ai-studio" },
  { label: "Engineering Library", href: "/engineering-library", icon: "EL", description: "Reusable standards", slug: "engineering-library" },
  { label: "Projects", href: "/projects", icon: "PJ", description: "Roadmaps and timelines", slug: "projects" },
  { label: "Reports", href: "/reports", icon: "RP", description: "Performance and quality", slug: "reports" },
  { label: "Settings", href: "/settings", icon: "ST", description: "Permissions and integrations", slug: "settings" },
] as const;

const MODULES: readonly ModuleConfig[] = [
  {
    slug: "missions",
    label: "AI Missions",
    stage: "Guided",
    summary: "Run guided AI missions to move products from concept to production with structured outcomes.",
    goals: ["Select mission", "Review generated plan", "Approve execution"],
    decisions: ["Priority mission", "Owner", "Approval level"],
    questions: ["What mission creates the most leverage this week?"],
  },
  {
    slug: "product-studio",
    label: "Product Studio",
    stage: "Idea to Versioning",
    summary: "Track product ideas, specs, images, versions, and roadmap decisions in one lifecycle timeline.",
    goals: ["Capture idea", "Promote to active product", "Define Version 2 objective"],
    decisions: ["Problem priority", "Portfolio rank", "Version gate"],
    questions: ["Which customer problem has highest impact?"],
  },
  {
    slug: "market-intelligence",
    label: "Market Intelligence",
    stage: "Research",
    summary: "Summarize demand, competitor moves, reviews, pricing, and market-gap opportunities.",
    goals: ["Run competitor scan", "Score market gaps", "Extract pain points"],
    decisions: ["Opportunity threshold", "Price position", "Feature edge"],
    questions: ["Is this category still worth entering?"],
  },
  {
    slug: "requirements",
    label: "Requirements",
    stage: "Definition",
    summary: "Create PRDs with dimensions, materials, manufacturing method, quality, packaging, and risk.",
    goals: ["Draft PRD", "Align constraints", "Approve requirements"],
    decisions: ["Target margin", "Quality grade", "Manufacturing route"],
    questions: ["What should not be compromised in Version 1?"],
  },
  {
    slug: "cad-studio",
    label: "CAD Studio",
    stage: "Design",
    summary: "Manage STEP, STL, DXF, SVG, PDF, and image assets with revision history and model controls.",
    goals: ["Upload model", "Track revision", "Review assembly"],
    decisions: ["Parametric strategy", "Tolerance limits", "Release candidate"],
    questions: ["Can this geometry be simplified before prototyping?"],
  },
  {
    slug: "material-studio",
    label: "Material Studio",
    stage: "Material Planning",
    summary: "Compare material options, suppliers, stock levels, cut lists, and waste impact.",
    goals: ["Select material set", "Optimize sheet usage", "Validate stock"],
    decisions: ["Supplier mix", "Waste tolerance", "Substitution rules"],
    questions: ["Which material lowers cost without weakening quality?"],
  },
  {
    slug: "cost-studio",
    label: "Cost Studio",
    stage: "Commercial Viability",
    summary: "Calculate material, machine, labor, packaging, shipping, fees, ROI, and break-even.",
    goals: ["Generate cost model", "Set price band", "Approve go/no-go"],
    decisions: ["Target ROI", "Break-even window", "Cash recovery"],
    questions: ["Is this product commercially viable at expected volume?"],
  },
  {
    slug: "prototype-studio",
    label: "Prototype Studio",
    stage: "Validation",
    summary: "Manage prototype versions, engineering notes, test outcomes, and approval workflows.",
    goals: ["Build prototype", "Record tests", "Approve iteration"],
    decisions: ["Iteration scope", "Defect severity", "Release readiness"],
    questions: ["What failed and what must change next?"],
  },
  {
    slug: "manufacturing-studio",
    label: "Manufacturing Studio",
    stage: "Production Readiness",
    summary: "Organize CNC programs, laser files, jigs, fixtures, setup docs, and quality checklists.",
    goals: ["Prepare assets", "Validate setup", "Lock instructions"],
    decisions: ["Machine plan", "Tooling", "Quality checkpoints"],
    questions: ["Which setup changes reduce cycle time?"],
  },
  {
    slug: "production-studio",
    label: "Production Studio",
    stage: "Execution",
    summary: "Schedule and track production orders, job cards, work centers, operators, and inspections.",
    goals: ["Issue job cards", "Track progress", "Close inspection"],
    decisions: ["Work center allocation", "Shift plan", "Packaging handoff"],
    questions: ["Where is throughput currently constrained?"],
  },
  {
    slug: "inventory-studio",
    label: "Inventory Studio",
    stage: "Stock Control",
    summary: "Monitor raw materials, hardware, WIP, finished goods, and channel inventory levels.",
    goals: ["Set reorder levels", "Map warehouse slots", "Reduce stock-outs"],
    decisions: ["Safety stock", "Allocation", "Replenishment trigger"],
    questions: ["Which SKU risks stock-out next?"],
  },
  {
    slug: "sales-studio",
    label: "Sales Studio",
    stage: "Go-to-Market",
    summary: "Coordinate Amazon, website, Etsy, eBay, wholesale, and B2B channels with returns and revenue tracking.",
    goals: ["Publish listings", "Track orders", "Analyze channel profit"],
    decisions: ["Channel split", "Promo strategy", "Returns policy"],
    questions: ["Which channel is most profitable for this product?"],
  },
  {
    slug: "ai-studio",
    label: "AI Studio",
    stage: "Decision Support",
    summary: "Use an engineering-focused AI assistant for design, cost, and manufacturing optimization tasks.",
    goals: ["Ask targeted prompts", "Review alternatives", "Apply approved recommendations"],
    decisions: ["Prompt pack", "Approval flow", "Execution mode"],
    questions: ["What should Version 2 improve first?"],
  },
  {
    slug: "engineering-library",
    label: "Engineering Library",
    stage: "Knowledge",
    summary: "Store reusable standards, parts, templates, best practices, and lessons learned.",
    goals: ["Capture standards", "Version templates", "Share lessons"],
    decisions: ["Library taxonomy", "Review cycle", "Access control"],
    questions: ["What standards should every new product inherit?"],
  },
  {
    slug: "projects",
    label: "Projects",
    stage: "Program Control",
    summary: "Run project plans, milestones, and ownership across product lifecycle workstreams.",
    goals: ["Define milestones", "Assign owners", "Track risk"],
    decisions: ["Timeline priority", "Resource loading", "Escalation path"],
    questions: ["Which milestone threatens launch date?"],
  },
  {
    slug: "reports",
    label: "Reports",
    stage: "Insights",
    summary: "Review progress, quality, cost, and market outcomes to drive continuous improvement.",
    goals: ["Generate report", "Compare versions", "Share executive summary"],
    decisions: ["KPI set", "Cadence", "Action owner"],
    questions: ["Which metric signals Version 2 urgency?"],
  },
  {
    slug: "settings",
    label: "Settings",
    stage: "Platform Governance",
    summary: "Manage tenants, roles, integrations, and policy controls for safe execution.",
    goals: ["Configure permissions", "Set integrations", "Audit activity"],
    decisions: ["Role matrix", "Token policy", "Notification rules"],
    questions: ["Are approvals strict enough for production actions?"],
  },
] as const;

export function getModuleBySlug(slug: string): ModuleConfig | undefined {
  return MODULES.find((entry) => entry.slug === slug);
}

export const PRODUCT_MODULES: readonly ModuleConfig[] = MODULES;
